
name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Adjust this according to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build and test
        run: npm run build

      - name: Deploy to EC2
        run: |
        
          scp -i path/to/your/key.pem -r ./dist/* ec2-user@your-ec2-ip:/path/to/app
          ssh -i path/to/your/key.pem ec2-user@your-ec2-ip "cd /path/to/app && npm install && pm2 restart your-app"
