name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 52.22.48.83 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@52.22.48.83 "cd /path/to/your/app && git pull origin main && npm install && pm2 restart aws-ec2"
        env:
          NODE_ENV: production
